import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:4199/', { waitUntil: 'networkidle' })
await page.waitForTimeout(800)
await page.screenshot({ path: `${out}/v3-overview.png` })
await page.getByRole('button', { name: /Take a look/ }).click()
await page.waitForTimeout(1200)
await page.screenshot({ path: `${out}/v3-tour1.png` })
await page.getByRole('button', { name: 'Next →' }).click()
await page.waitForTimeout(1200)
await page.screenshot({ path: `${out}/v3-tour2-budget.png` })
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
console.log('h-overflow:', overflow)
await browser.close()
